"""
WAR ROOM — Scenario Routes
Polling endpoints for the assembling/briefing screen.
GET /api/sessions/{session_id}/scenario       → scenario status + full spec
GET /api/sessions/{session_id}/scenario/skill/{agent_id} → agent SKILL.md
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import JSONResponse

from utils.auth import get_chairman_token, validate_chairman_token
from utils.firestore_helpers import _get_db
from utils.voice_discovery import discover_voices
from config.constants import (
    COLLECTION_CRISIS_SESSIONS,
    COLLECTION_AGENT_SKILLS,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/sessions", tags=["Scenario"])


# ── GET /api/sessions/{session_id}/scenario ──────────────────────────────


@router.get("/{session_id}/scenario")
async def get_scenario(
    session_id: str,
    token: str = Depends(get_chairman_token),
):
    """
    Get the full scenario spec generated by the Scenario Analyst.
    Frontend polls this during the assembling screen.

    Returns 200 when scenario_ready=True, 202 when still assembling.
    """
    session_data = await validate_chairman_token(session_id, token)

    scenario_ready = session_data.get("scenario_ready", False)
    assembly_log = session_data.get("assembly_log", [])

    if not scenario_ready:
        # Still assembling — return 202
        return JSONResponse(
            status_code=202,
            content={
                "scenario_ready": False,
                "assembly_log": assembly_log,
                "message": "Scenario analyst still running. Retry in 1 second.",
            },
        )

    # Scenario is ready — return full spec
    scenario_spec = session_data.get("scenario_spec", {})
    agent_roster = session_data.get("agent_roster", [])

    # Build agent list for scenario response
    agents = []
    for agent in agent_roster:
        agents.append({
            "agent_id": agent.get("agent_id", ""),
            "role_key": agent.get("agent_id", "").rsplit("_", 1)[0] if agent.get("agent_id") else "",
            "role_title": agent.get("role_title", ""),
            "character_name": agent.get("character_name", ""),
            "defining_line": agent.get("defining_line", ""),
            "identity_color": agent.get("identity_color", "#666"),
            "voice_name": agent.get("voice_name", ""),
            "status": agent.get("status", "idle"),
        })

    return {
        "session_id": session_id,
        "crisis_title": session_data.get("crisis_title", ""),
        "crisis_domain": session_data.get("crisis_domain", ""),
        "crisis_brief": session_data.get("crisis_brief", ""),
        "scenario_instruction_guide": session_data.get("scenario_instruction_guide", ""),
        "voice_runtime": session_data.get("voice_runtime", {}),
        "threat_level_initial": scenario_spec.get(
            "threat_level_initial",
            session_data.get("threat_level", "elevated"),
        ),
        "resolution_score_initial": scenario_spec.get(
            "resolution_score_initial",
            session_data.get("resolution_score", 50),
        ),
        "agents": agents,
        "initial_intel": scenario_spec.get("initial_intel", []),
        "initial_conflicts": scenario_spec.get("initial_conflicts", []),
        "escalation_schedule": scenario_spec.get("escalation_schedule", []),
        "assembly_log": assembly_log,
        "scenario_ready": True,
    }


# ── GET /api/sessions/{session_id}/scenario/skill/{agent_id} ─────────────


@router.get("/{session_id}/scenario/skill/{agent_id}")
async def get_agent_skill(
    session_id: str,
    agent_id: str,
    token: str = Depends(get_chairman_token),
):
    """
    Read the generated SKILL.md for any agent.
    Useful for transparency and debugging agent behavior.
    Voice names are validated against the Google API's available voice pool.

    MEMORY ISOLATION:
    Returns ONLY skill_md (the instruction given to the agent).
    Does NOT return agent's private memory, hidden knowledge,
    or previous statements.
    """
    await validate_chairman_token(session_id, token)

    db = _get_db()

    # Try to find the skill document.
    # Convention: document ID is {session_id}_{agent_id}  or  {session_id}_{role_key}
    skill_doc = await db.collection(COLLECTION_AGENT_SKILLS) \
                        .document(f"{session_id}_{agent_id}").get()

    if not skill_doc.exists:
        raise HTTPException(
            status_code=404,
            detail=f"Skill document not found for agent {agent_id}",
        )

    skill_data = skill_doc.to_dict()
    skill_md = skill_data.get("skill_md", "")

    # Look up character name and role from the session roster
    session_doc = await db.collection(COLLECTION_CRISIS_SESSIONS) \
                          .document(session_id).get()

    character_name = ""
    role_title = ""
    voice_name = skill_data.get("voice_name", "")

    if session_doc.exists:
        roster = session_doc.to_dict().get("agent_roster", [])
        for agent in roster:
            aid = agent.get("agent_id", "")
            rkey = aid.rsplit("_", 1)[0] if aid else ""
            if agent_id in (aid, rkey):
                character_name = agent.get("character_name", "")
                role_title = agent.get("role_title", "")
                voice_name = agent.get("voice_name", voice_name)
                break

    # Validate voice name against the Google API's available pool
    available_voices = await discover_voices()
    if voice_name and voice_name not in available_voices:
        logger.warning(
            f"Voice '{voice_name}' assigned to {agent_id} is not in the "
            f"Google API voice pool ({len(available_voices)} voices available)"
        )

    return {
        "agent_id": agent_id,
        "character_name": character_name,
        "role_title": role_title,
        "voice_name": voice_name,
        "skill_md": skill_md,
        "generated_at": str(skill_data.get("generated_at", "")),
        "word_count": len(skill_md.split()) if skill_md else 0,
    }
